import '../models/tool_models.dart';

const _videoExtensions = ['mp4', 'mov', 'mkv', 'webm'];
const _audioExtensions = ['mp3', 'wav', 'aac', 'm4a'];
const _imageExtensions = ['jpg', 'jpeg', 'png', 'webp', 'heic'];

const mvpTools = [
  ToolDefinition(
    id: 'video.convert',
    title: '视频格式转换',
    description: '转换为 MP4、MOV、MKV 或 WebM 等常见格式。',
    category: MediaKind.video,
    acceptedInputs: [MediaKind.video],
    supportedInputExtensions: _videoExtensions,
    supportedInputMimeTypes: ['video/*'],
    outputFormats: ['mp4', 'mov', 'mkv', 'webm'],
    defaultOutputFormat: 'mp4',
    defaultPresetId: 'recommended',
    presets: [
      ToolPreset(
        id: 'recommended',
        title: '推荐',
        outputExtension: 'mp4',
        parameters: {'quality': 'balanced'},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['MP4', 'MOV', 'WebM'],
  ),
  ToolDefinition(
    id: 'video.compress',
    title: '视频压缩',
    description: '减小视频体积，方便发送和分享。',
    category: MediaKind.video,
    acceptedInputs: [MediaKind.video],
    supportedInputExtensions: _videoExtensions,
    supportedInputMimeTypes: ['video/*'],
    outputFormats: ['mp4'],
    defaultOutputFormat: 'mp4',
    defaultPresetId: 'balanced',
    presets: [
      ToolPreset(
        id: 'balanced',
        title: '推荐压缩',
        outputExtension: 'mp4',
        parameters: {'quality': 'balanced'},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['压缩', '分享'],
  ),
  ToolDefinition(
    id: 'video.extractAudio',
    title: '视频转音频',
    description: '从视频中导出 MP3 或 AAC 音频。',
    category: MediaKind.video,
    acceptedInputs: [MediaKind.video],
    supportedInputExtensions: _videoExtensions,
    supportedInputMimeTypes: ['video/*'],
    outputFormats: ['mp3', 'aac', 'm4a'],
    defaultOutputFormat: 'mp3',
    defaultPresetId: 'mp3',
    presets: [
      ToolPreset(
        id: 'mp3',
        title: 'MP3',
        outputExtension: 'mp3',
        parameters: {'audioBitrate': '192k'},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['MP3', '提取'],
  ),
  ToolDefinition(
    id: 'audio.convert',
    title: '音频格式转换',
    description: '转换为 MP3、WAV、AAC 等常用音频格式。',
    category: MediaKind.audio,
    acceptedInputs: [MediaKind.audio],
    supportedInputExtensions: _audioExtensions,
    supportedInputMimeTypes: ['audio/*'],
    outputFormats: ['mp3', 'wav', 'aac', 'm4a'],
    defaultOutputFormat: 'mp3',
    defaultPresetId: 'mp3',
    presets: [
      ToolPreset(
        id: 'mp3',
        title: 'MP3',
        outputExtension: 'mp3',
        parameters: {'audioBitrate': '192k'},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['MP3', 'WAV', 'AAC'],
  ),
  ToolDefinition(
    id: 'audio.compress',
    title: '音频压缩',
    description: '压缩音频体积，保留适合分享的音质。',
    category: MediaKind.audio,
    acceptedInputs: [MediaKind.audio],
    supportedInputExtensions: _audioExtensions,
    supportedInputMimeTypes: ['audio/*'],
    outputFormats: ['mp3', 'aac'],
    defaultOutputFormat: 'mp3',
    defaultPresetId: 'small',
    presets: [
      ToolPreset(
        id: 'small',
        title: '较小体积',
        outputExtension: 'mp3',
        parameters: {'audioBitrate': '128k'},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['压缩', 'MP3'],
  ),
  ToolDefinition(
    id: 'image.convert',
    title: '图片格式转换',
    description: '转换 JPG、PNG、WebP 等图片格式。',
    category: MediaKind.image,
    acceptedInputs: [MediaKind.image],
    supportedInputExtensions: _imageExtensions,
    supportedInputMimeTypes: ['image/*'],
    outputFormats: ['jpg', 'png', 'webp'],
    defaultOutputFormat: 'jpg',
    defaultPresetId: 'jpg',
    presets: [
      ToolPreset(
        id: 'jpg',
        title: 'JPG',
        outputExtension: 'jpg',
        parameters: {'quality': 90},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['JPG', 'PNG', 'WebP'],
  ),
  ToolDefinition(
    id: 'image.compress',
    title: '图片压缩',
    description: '减小图片体积，适合上传和发送。',
    category: MediaKind.image,
    acceptedInputs: [MediaKind.image],
    supportedInputExtensions: _imageExtensions,
    supportedInputMimeTypes: ['image/*'],
    outputFormats: ['jpg', 'webp'],
    defaultOutputFormat: 'jpg',
    defaultPresetId: 'balanced',
    presets: [
      ToolPreset(
        id: 'balanced',
        title: '推荐压缩',
        outputExtension: 'jpg',
        parameters: {'quality': 80},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['压缩', 'JPG'],
  ),
  ToolDefinition(
    id: 'image.heicToJpg',
    title: 'HEIC 转 JPG/PNG',
    description: '把 iPhone HEIC 图片转换为更通用的格式。',
    category: MediaKind.image,
    acceptedInputs: [MediaKind.image],
    supportedInputExtensions: ['heic', 'heif'],
    supportedInputMimeTypes: ['image/heic', 'image/heif'],
    outputFormats: ['jpg', 'png'],
    defaultOutputFormat: 'jpg',
    defaultPresetId: 'jpg',
    presets: [
      ToolPreset(
        id: 'jpg',
        title: 'JPG',
        outputExtension: 'jpg',
        parameters: {'quality': 92},
      ),
    ],
    parameterSchema: ToolParameterSchema(),
    allowMultipleInputs: true,
    isMvp: true,
    tags: ['HEIC', 'JPG'],
  ),
];
